import {
    Button,
    VerticalBox,
    LineEdit,
    Spinner,
    HorizontalBox,
    ComboBox,
    Palette,
} from "std-widgets.slint";
import { Tabs, TabBar, TabBarButton, TabBody, Tab } from "tab.slint";
import { CustomPalette } from "palette.slint";

enum LoginStatus {
    Waiting,
    Confirming,
    Expired,
    Success,
}

enum RoomIdStatus {
    Fetching,
    Ok,
    Failed,
}

enum LiveStatus {
    Off,
    Living,
}

struct Protocol {
    name: string,
    addr: string,
    code: string,
}

export global Logic {
    // Notifications
    in-out property <[string]> notifications: [];

    // Platform
    callback copy-to-clipboard(text: string);

    // Login
    in-out property <image> qr-code;
    in-out property <LoginStatus> login-status: LoginStatus.Waiting;
    in-out property <string> oauth-key;
    in-out property <bool> qr-code-ready: false;
    callback refresh-qr-code();
    callback logout();

    // User
    in-out property <image> face;
    in-out property <string> uname;
    in-out property <string> user-id;
    in-out property <string> room-id;
    in-out property <RoomIdStatus> room-id-status: RoomIdStatus.Fetching;

    // Live
    in-out property <string> title;
    in-out property <[string]> area-list: [];
    in-out property <string> selected-area;
    in-out property <[string]> sub-area-list: [];
    in-out property <string> selected-sub-area;
    callback update-sub-area-list();
    callback update-live-area();
    callback update-live-title();
    in-out property <LiveStatus> live-status: LiveStatus.Off;
    in-out property <[Protocol]> protocols: [];
    callback start-live();
    callback stop-live();
    in-out property <image> face-verfication-qr-code;
    in-out property <bool> face-verfication-qr-code-ready: false;
}

component QrCode {
    in property <image> source;
    in property <bool> ready;
    width: 300px;
    height: 300px;

    if ready: Image {
        width: 300px;
        height: 300px;
        source: source;
        image-fit: contain;
        image-rendering: pixelated;
    }

    if !ready: Rectangle {
        width: 300px;
        height: 300px;
        background: #eee;
        border-radius: 10px;

        Spinner {
            indeterminate: true;
        }
    }
}

component LoginPage {
    VerticalBox {
        Text {
            text: Logic.login-status == LoginStatus.Waiting ? "请使用B站APP扫码登录" :      //
                   Logic.login-status == LoginStatus.Confirming ? "请在手机上确认登录" :     //
                   Logic.login-status == LoginStatus.Expired ? "二维码已过期，请刷新" :       //
                   Logic.login-status == LoginStatus.Success ? "登录成功！" : "未知状态";    //
            horizontal-alignment: center;
        }

        QrCode {
            source: Logic.qr-code;
            ready: Logic.qr-code-ready;
        }

        Button {
            text: "刷新二维码";
            clicked => Logic.refresh-qr-code();
        }
    }
}

component InfoLine {
    in property <string> label;
    in property <string> text;
    in property <bool> enable: true;

    HorizontalBox {
        padding: 0;
        Text {
            text: label;
            width: 40px;
            vertical-alignment: center;
        }

        LineEdit {
            text: text;
            read-only: true;
        }

        Button {
            text: "复制";
            enabled: enable;
            clicked => Logic.copy-to-clipboard(text);
        }
    }
}

component ProtocolInfoTabs {
    property <int> active-tab;

    Tabs {
        TabBar {
            for protocol[index] in Logic.protocols: TabBarButton {
                title: protocol.name;
                index: index;
                active-tab <=> root.active-tab;
            }
        }

        TabBody {
            width: root.width;
            height: 100px;

            for protocol[index] in Logic.protocols: Tab {
                index: index;
                active-tab <=> root.active-tab;
                tab-width: root.width;

                InfoLine {
                    label: "服务器";
                    text: protocol.addr;
                    enable: protocol.addr != "";
                }

                InfoLine {
                    label: "推流码";
                    text: protocol.code;
                    enable: protocol.code != "";
                }
            }
        }
    }
}

component MainPage {
    VerticalBox {
        HorizontalBox {
            Rectangle {
                width: 40px;
                height: 40px;
                clip: true;
                border-radius: 20px;
                Image {
                    width: parent.width;
                    height: parent.height;
                    source: Logic.face;
                }
            }

            Text {
                text: Logic.uname;
                font-size: 15px;
                vertical-alignment: center;
            }

            Button {
                text: "退出登录";
                clicked => Logic.logout();
            }
        }

        VerticalBox {
            width: 450px;
            Text {
                text: "房间号: " + (Logic.room-id-status == RoomIdStatus.Fetching ? "获取中..." :  //
                       Logic.room-id-status == RoomIdStatus.Ok ? Logic.room-id :  //
                       Logic.room-id-status == RoomIdStatus.Failed ? "获取失败" : "未知状态");    //
            }

            if Logic.live-status != LiveStatus.Living:  VerticalBox {
                padding: 0;

                HorizontalBox {
                    padding: 0;

                    Text {
                        text: "标题";
                        vertical-alignment: center;
                    }

                    LineEdit {
                        text <=> Logic.title;
                        placeholder-text: "请输入直播标题";
                    }

                    Button {
                        text: "更新";
                        clicked => Logic.update-live-title();
                    }
                }

                HorizontalBox {
                    padding: 0;

                    Text {
                        text: "分区";
                        vertical-alignment: center;
                    }

                    ComboBox {
                        model: Logic.area-list;
                        current-value <=> Logic.selected-area;
                        selected => Logic.update-sub-area-list();
                    }

                    ComboBox {
                        model: Logic.sub-area-list;
                        current-value <=> Logic.selected-sub-area;
                    }

                    Button {
                        text: "更新";
                        clicked => Logic.update-live-area();
                    }
                }

                Text {
                    text: "开始直播时自动更新标题和分区";
                    font-size: 12px;
                    horizontal-alignment: center;
                    color: Palette.foreground.transparentize(60%);
                }

                Button {
                    text: "开始直播";
                    primary: true;
                    clicked => Logic.start-live();
                }
            }

            if Logic.live-status == LiveStatus.Living: VerticalBox {
                padding: 0;

                if Logic.protocols.length > 0:
                ProtocolInfoTabs {
                    width: parent.width;
                }

                Button {
                    text: "结束直播";
                    primary: true;
                    clicked => Logic.stop-live();
                }
            }
        }
    }
}

component Notifications {
    VerticalBox {
        for notification in Logic.notifications: HorizontalLayout {
            alignment: center;
            Rectangle {
                border-radius: 5px;
                background: Palette.control-background;
                width: text.preferred-width + 20px;

                HorizontalBox {
                    text := Text {
                        text: notification;
                        color: Palette.control-foreground;
                        vertical-alignment: center;
                        horizontal-alignment: center;

                        opacity: 0.0;
                        init => {
                            self.opacity = 1.0;
                        }
                        animate opacity { duration: 0.2s; }
                    }
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    title: "Bili Live Tool";
    preferred-width: 600px;
    preferred-height: 500px;

    if Logic.login-status != LoginStatus.Success: LoginPage { }
    if Logic.login-status == LoginStatus.Success: MainPage { }

    public function show-popup() {
        popup.show();
    }

    popup := PopupWindow {
        close-policy: no-auto-close;
        x: (parent.width - self.preferred-width) / 2;
        y: (parent.height - self.preferred-height) / 2;

        Rectangle {
            palette := CustomPalette { }

            background: Palette.background;
            border-radius: 10px;
            drop-shadow-blur: 2px;
            drop-shadow-color: Palette.foreground.transparentize(80%);

            VerticalBox {
                padding: 10px;

                Text {
                    text: "请使用B站APP扫码完成人脸验证";
                    horizontal-alignment: center;
                }

                QrCode {
                    ready: Logic.face-verfication-qr-code-ready;
                    source: Logic.face-verfication-qr-code;
                }

                Button {
                    text: "我已完成验证";
                    clicked => {
                        popup.close();
                        Logic.start-live();
                    }
                }
            }
        }
    }

    notifications := Notifications {
        y: 0;
    }
}
