import {
    Button,
    VerticalBox,
    LineEdit,
    AboutSlint,
    Spinner,
    HorizontalBox,
    ComboBox,
    StyleMetrics,
    Palette,
} from "std-widgets.slint";

enum LoginStatus {
    Waiting,
    Confirming,
    Expired,
    Success,
}

enum RoomIdStatus {
    Fetching,
    Ok,
    Failed,
}

export global Logic {
    // Notifications
    in-out property <[string]> notifications: [];

    // Login
    in-out property <image> qr-code;
    in-out property <LoginStatus> login-status: LoginStatus.Waiting;
    in-out property <string> oauth-key;
    in-out property <bool> qr-code-ready: false;
    callback refresh-qr-code();
    callback logout();

    // User
    in-out property <image> face;
    in-out property <string> uname;
    in-out property <string> room-id;
    in-out property <RoomIdStatus> room-id-status: RoomIdStatus.Fetching;

    // Live
    in-out property <string> title;
    in-out property <[string]> area-list;
    in-out property <string> selected-area;
    in-out property <[string]> sub-area-list;
    in-out property <string> selected-sub-area;
    callback update-sub-area-list();
    callback update-live-area();
    callback update-live-title();
}

component LoginPage {
    VerticalBox {
        Text {
            text: Logic.login-status == LoginStatus.Waiting ? "请使用B站APP扫码登录" :      //
                   Logic.login-status == LoginStatus.Confirming ? "请在手机上确认登录" :     //
                   Logic.login-status == LoginStatus.Expired ? "二维码已过期，请刷新" :       //
                   Logic.login-status == LoginStatus.Success ? "登录成功！" : "未知状态";    //
            horizontal-alignment: center;
        }

        if Logic.qr-code-ready:
        Image {
            width: 300px;
            height: 300px;
            source: Logic.qr-code;
            image-fit: contain;
            image-rendering: pixelated;
        }

        if !Logic.qr-code-ready:
        Rectangle {
            width: 300px;
            height: 300px;
            background: #eee;
            border-radius: 10px;

            Spinner {
                indeterminate: true;
            }
        }

        Button {
            text: "刷新二维码";
            clicked => Logic.refresh-qr-code();
        }
    }
}

component MainPage {
    VerticalBox {
        HorizontalBox {
            Rectangle {
                width: 40px;
                height: 40px;
                clip: true;
                border-radius: 20px;
                Image {
                    width: parent.width;
                    height: parent.height;
                    source: Logic.face;
                }
            }

            Text {
                text: Logic.uname;
                font-size: 15px;
                vertical-alignment: center;
            }

            Button {
                text: "退出登录";
                clicked => Logic.logout();
            }
        }

        VerticalBox {
            Text {
                text: "房间号: " + (Logic.room-id-status == RoomIdStatus.Fetching ? "获取中..." :  //
                       Logic.room-id-status == RoomIdStatus.Ok ? Logic.room-id :  //
                       Logic.room-id-status == RoomIdStatus.Failed ? "获取失败" : "未知状态");    //
            }

            HorizontalBox {
                padding: 0;

                Text {
                    text: "标题";
                    vertical-alignment: center;
                }

                LineEdit {
                    text <=> Logic.title;
                    placeholder-text: "请输入直播标题";
                }

                Button {
                    text: "更新";
                    clicked => Logic.update-live-title();
                }
            }

            HorizontalBox {
                padding: 0;

                Text {
                    text: "分区";
                    vertical-alignment: center;
                }

                ComboBox {
                    model: Logic.area-list;
                    current-value <=> Logic.selected-area;
                    selected => Logic.update-sub-area-list();
                }

                ComboBox {
                    model: Logic.sub-area-list;
                    current-value <=> Logic.selected-sub-area;
                }

                Button {
                    text: "更新";
                    clicked => Logic.update-live-area();
                }
            }

            Button {
                text: "开始直播";
                primary: true;
            }
        }
    }
}

component Notifications {
    VerticalBox {
        for notification in Logic.notifications: Rectangle {
            border-radius: 5px;
            background: Palette.control-background;

            HorizontalBox {
                Text {
                    text: notification;
                    color: Palette.control-foreground;
                    vertical-alignment: center;
                    horizontal-alignment: center;

                    opacity: 0.0;
                    init => {
                        self.opacity = 1.0;
                    }
                    animate opacity { duration: 0.2s; }
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    title: "Bili Live Tool";
    width: 600px;
    height: 500px;

    if Logic.login-status != LoginStatus.Success: LoginPage { }
    if Logic.login-status == LoginStatus.Success: MainPage { }

    notifications := Notifications {
        y: 0;
    }
}
