import {
    Button,
    VerticalBox,
    LineEdit,
    AboutSlint,
    Spinner,
    HorizontalBox,
    ComboBox,
    StyleMetrics,
    Palette,
    TabWidget,
} from "std-widgets.slint";

enum LoginStatus {
    Waiting,
    Confirming,
    Expired,
    Success,
}

enum RoomIdStatus {
    Fetching,
    Ok,
    Failed,
}

enum LiveStatus {
    Off,
    Living,
}

struct Protocol {
    name: string,
    addr: string,
    code: string,
}

export global Logic {
    // Notifications
    in-out property <[string]> notifications: [];

    // Platform
    callback copy-to-clipboard(text: string);

    // Login
    in-out property <image> qr-code;
    in-out property <LoginStatus> login-status: LoginStatus.Waiting;
    in-out property <string> oauth-key;
    in-out property <bool> qr-code-ready: false;
    callback refresh-qr-code();
    callback logout();

    // User
    in-out property <image> face;
    in-out property <string> uname;
    in-out property <string> room-id;
    in-out property <RoomIdStatus> room-id-status: RoomIdStatus.Fetching;

    // Live
    in-out property <string> title;
    in-out property <[string]> area-list: [];
    in-out property <string> selected-area;
    in-out property <[string]> sub-area-list: [];
    in-out property <string> selected-sub-area;
    callback update-sub-area-list();
    callback update-live-area();
    callback update-live-title();
    in-out property <LiveStatus> live-status: LiveStatus.Living;
    in-out property <[Protocol]> protocols: [
        {
            name: "RTMP",
            addr: "rtmp://example.com/live",
            code: "123456",
        },
        {
            name: "SRT",
            addr: "srt://example.com:1234",
            code: "abcdef",
        }
    ];
    callback start-live();
    callback stop-live();
}

component CustomPalette {
    width: 0;
    height: 0;

    public pure function border() -> brush {
        Palette.color-scheme == ColorScheme.dark ? oklch(0.333, 0, 0) : oklch(0.630, 0, 0)
    }

    public pure function background() -> brush {
        Palette.color-scheme == ColorScheme.dark ? oklch(0.2264, 0, 0) : oklch(0.985, 0, 0)
    }

    public pure function accent(base: brush) -> brush {
        Palette.color-scheme == ColorScheme.dark ? base.brighter(50%) : base.darker(50%)
    }

    public pure function decent(base: brush) -> brush {
        Palette.color-scheme == ColorScheme.dark ? base.darker(50%) : base.brighter(50%)
    }
}

component LoginPage {
    VerticalBox {
        Text {
            text: Logic.login-status == LoginStatus.Waiting ? "请使用B站APP扫码登录" :      //
                   Logic.login-status == LoginStatus.Confirming ? "请在手机上确认登录" :     //
                   Logic.login-status == LoginStatus.Expired ? "二维码已过期，请刷新" :       //
                   Logic.login-status == LoginStatus.Success ? "登录成功！" : "未知状态";    //
            horizontal-alignment: center;
        }

        if Logic.qr-code-ready:
        Image {
            width: 300px;
            height: 300px;
            source: Logic.qr-code;
            image-fit: contain;
            image-rendering: pixelated;
        }

        if !Logic.qr-code-ready:
        Rectangle {
            width: 300px;
            height: 300px;
            background: #eee;
            border-radius: 10px;

            Spinner {
                indeterminate: true;
            }
        }

        Button {
            text: "刷新二维码";
            clicked => Logic.refresh-qr-code();
        }
    }
}

component InfoLine {
    in property <string> label;
    in property <string> text;
    in property <bool> enable;

    HorizontalBox {
        padding: 0;
        Text {
            text: label;
            width: 40px;
            vertical-alignment: center;
        }

        LineEdit {
            text: text;
            read-only: true;
        }

        Button {
            text: "复制";
            enabled: enable;
            clicked => Logic.copy-to-clipboard(text);
        }
    }
}

component ProtocolInfoTabs {
    in-out property <int> active-tab;
    VerticalLayout {
        spacing: -1px;

        tab_bar := HorizontalLayout {
            spacing: -1px;
            padding-left: 1px;
            padding-right: 0px;

            palette := CustomPalette { }

            for protocol[index] in Logic.protocols: Rectangle {
                border-top-left-radius: 5px;
                border-top-right-radius: 5px;
                border-width: 1px;
                border-color: root.active-tab == index ? palette.border() : palette.decent(palette.border());
                background: touch.pressed ? palette.accent(palette.accent(palette.background())) : touch.has-hover ? palette.accent(palette.background()) : palette.background();
                height: txt.preferred-height * 2;
                min-width: txt.preferred-width + 20px;
                txt := Text {
                    x: (parent.width - self.width) / 2 + (touch.pressed ? 2px : 0);
                    y: (parent.height - self.height) / 2 + (touch.pressed ? 1px : 0);
                    text: protocol.name;
                    color: Palette.foreground;
                }

                touch := TouchArea {
                    clicked => {
                        root.active-tab = index;
                    }
                }
            }
        }

        Rectangle {
            clip: true;
            width: measure.preferred-width;
            height: measure.preferred-height;
            border-color: Palette.border;
            border-width: 1px;
            border-bottom-left-radius: 5px;
            border-bottom-right-radius: 5px;

            measure := VerticalBox {
                padding: 10px;
                visible: false;

                InfoLine {
                    enable: false;
                }

                InfoLine {
                    enable: false;
                }
            }

            for protocol[index] in Logic.protocols: VerticalBox {
                padding: 10px;
                x: root.active-tab == index ? 0 : root.active-tab < index ? - self.width - 1px : parent.width + 1px;
                animate x {
                    duration: 125ms;
                    easing: ease;
                }

                InfoLine {
                    label: "地址";
                    text: protocol.addr;
                }

                InfoLine {
                    label: "房间码";
                    text: protocol.code;
                }
            }
        }
    }
}

component MainPage {
    VerticalBox {
        HorizontalBox {
            Rectangle {
                width: 40px;
                height: 40px;
                clip: true;
                border-radius: 20px;
                Image {
                    width: parent.width;
                    height: parent.height;
                    source: Logic.face;
                }
            }

            Text {
                text: Logic.uname;
                font-size: 15px;
                vertical-alignment: center;
            }

            Button {
                text: "退出登录";
                clicked => Logic.logout();
            }
        }

        VerticalBox {
            Text {
                text: "房间号: " + (Logic.room-id-status == RoomIdStatus.Fetching ? "获取中..." :  //
                       Logic.room-id-status == RoomIdStatus.Ok ? Logic.room-id :  //
                       Logic.room-id-status == RoomIdStatus.Failed ? "获取失败" : "未知状态");    //
            }

            if Logic.live-status != LiveStatus.Living:  VerticalBox {
                padding: 0;

                HorizontalBox {
                    padding: 0;

                    Text {
                        text: "标题";
                        vertical-alignment: center;
                    }

                    LineEdit {
                        text <=> Logic.title;
                        placeholder-text: "请输入直播标题";
                    }

                    Button {
                        text: "更新";
                        clicked => Logic.update-live-title();
                    }
                }

                HorizontalBox {
                    padding: 0;

                    Text {
                        text: "分区";
                        vertical-alignment: center;
                    }

                    ComboBox {
                        model: Logic.area-list;
                        current-value <=> Logic.selected-area;
                        selected => Logic.update-sub-area-list();
                    }

                    ComboBox {
                        model: Logic.sub-area-list;
                        current-value <=> Logic.selected-sub-area;
                    }

                    Button {
                        text: "更新";
                        clicked => Logic.update-live-area();
                    }
                }

                Button {
                    text: "开始直播";
                    primary: true;
                    clicked => Logic.start-live();
                }
            }

            if Logic.live-status == LiveStatus.Living: VerticalBox {
                padding: 0;

                ProtocolInfoTabs { }

                Button {
                    text: "结束直播";
                    primary: true;
                    clicked => Logic.stop-live();
                }
            }
        }
    }
}

component Notifications {
    VerticalBox {
        for notification in Logic.notifications: Rectangle {
            border-radius: 5px;
            background: Palette.control-background;

            HorizontalBox {
                Text {
                    text: notification;
                    color: Palette.control-foreground;
                    vertical-alignment: center;
                    horizontal-alignment: center;

                    opacity: 0.0;
                    init => {
                        self.opacity = 1.0;
                    }
                    animate opacity { duration: 0.2s; }
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    title: "Bili Live Tool";
    preferred-width: 600px;
    preferred-height: 500px;

    if Logic.login-status != LoginStatus.Success: LoginPage { }
    if Logic.login-status == LoginStatus.Success: MainPage { }

    notifications := Notifications {
        y: 0;
    }
}
