import { Palette } from "std-widgets.slint";

export component CustomPalette {
    width: 0;
    height: 0;

    public pure function border() -> brush {
        Palette.color-scheme == ColorScheme.dark ? oklch(0.333, 0, 0) : oklch(0.900, 0, 0)
    }

    public pure function background() -> brush {
        Palette.color-scheme == ColorScheme.dark ? oklch(0.2264, 0, 0) : oklch(0.985, 0, 0)
    }

    public pure function accent(base: brush, percent: float) -> brush {
        Palette.color-scheme == ColorScheme.dark ? base.brighter(percent) : base.darker(percent)
    }

    public pure function decent(base: brush, percent: float) -> brush {
        Palette.color-scheme == ColorScheme.dark ? base.darker(percent) : base.brighter(percent)
    }
}
